# Generated by Django 5.2.5 on 2025-11-25 01:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_userregistration_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
